# Menggunakan Python 3.9 sebagai base image
FROM python:3.9-slim

# Menentukan working directory di container
WORKDIR /app

# Menyalin file deploy.py ke dalam container
COPY deploy.py /app/

# Menginstal dependensi yang diperlukan
RUN pip install --no-cache-dir fastapi[standard] uvicorn pydantic

# Menentukan perintah untuk menjalankan aplikasi menggunakan Uvicorn
CMD ["uvicorn", "deploy:app", "--host", "0.0.0.0", "--port", "8000"]