FROM python:3.10

RUN pip install mlflow psycopg2-binary boto3

WORKDIR /app

CMD ["mlflow", "server",  "--backend-store-uri", "postgresql+psycopg2://mlflow:irul12345@db/mlflow", "--host", "0.0.0.0", "--port", "5000", "--serve-artifacts", "--artifacts-destination", "gs://$GCS_BUCKET_NAME_TRACKER"]
