# Gunakan image Python yang ringan
FROM python:3.9-slim

# Set working directory di dalam container
WORKDIR /app

# Salin dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Salin semua kode project ke dalam container
COPY . .

# Ekspos port yang digunakan FastAPI
EXPOSE 8000

# Jalankan FastAPI menggunakan Uvicorn
CMD ["uvicorn", "deploy:app", "--host", "0.0.0.0", "--port", "8000"]
